### ISSUE TITLE
文字页游反馈_mjj

### ISSUE THREAD

**Issue by Hjieyye** [setube/vue-XiuXianGame#1]
可以托管架设像这样的文字游戏吗？搞起来让我们一起玩

https://wap.wm404.com

https://www.52pojie.cn/forum.php?mod=viewthread&tid=1545379

这种文字游戏运营10几年依然坚挺我只服"好玩吧 地狱之门"(曾经在腾讯QQ家园叫"魔界")
http://haowanba.com

**Comment by setube** [comment]
非反馈类议题
