### ISSUE TITLE
[BUG反馈] 批量出售遇到非整数炼器石

### ISSUE THREAD

**Issue by cxw620** [setube/vue-XiuXianGame#14]
**BUG描述**
![image](https://github.com/user-attachments/assets/ad98f969-c1c4-4d4a-9703-f09b89db4f7b)
批量出售遇到非整数炼器石

**存档数据**
[文字修仙小游戏存档2024-07-29 03_57_11.json](https://github.com/user-attachments/files/16405046/2024-07-29.03_57_11.json)

**Comment by setube** [comment]
你这个问题我其实已经修复了的

**Comment by setube** [comment]
已修复
