### ISSUE TITLE
[BUG反馈] 本地构建报错

### ISSUE THREAD

**Issue by NooAcc** [setube/vue-XiuXianGame#2]
**BUG描述**
按照步骤，在本地构建时，在`npm run build`这一步会报错，导致无法进行下去

**软件版本**
`node` 版本：v20.14.0
`npm` 版本：10.7.0

**运行日志**
`npm i` 日志如下:
[npm i.txt](https://github.com/user-attachments/files/16232632/npm.i.txt)

`npm build` 无效，于是使用`npm run build`

`npm run build` 日志如下：
[npm run build.txt](https://github.com/user-attachments/files/16232643/npm.run.build.txt)

**Comment by setube** [comment]
我版本node和npm版本都没你的高,我切换到和你同版本试下
