### ISSUE TITLE
[功能需求]屏幕高度适配的问题

### ISSUE THREAD

**Issue by cikichen** [setube/vue-XiuXianGame#27]
** 需求 **
尽可能描述清楚点

在小屏幕上（笔记本）会因为高度出现滚动条，导致看到上面就看不到下面，很影响体验
![QQ_1724896225032](https://github.com/user-attachments/assets/9a1be7d4-6e39-456d-ba15-00acada07acd)
![QQ_1724896244548](https://github.com/user-attachments/assets/a214bd0a-03b0-425c-adba-3c0d211dd5cc)
![QQ_1724896260555](https://github.com/user-attachments/assets/35a4af1c-67f5-41b0-892d-ba78868bafb9)
![QQ_1724896272875](https://github.com/user-attachments/assets/e1d52150-4cc1-49ef-9a22-31ee6e310777)

每次操作还要滚动下屏幕

我是macbook m1 pro

**Comment by setube** [comment]
好 下个版本解决

**Comment by setube** [comment]
新版本已解决
