### ISSUE TITLE
[求教]

### ISSUE THREAD

**Issue by Raymondwu12** [setube/vue-XiuXianGame#36]
萌新不知道源码怎么用，求求教程，macos

**Comment by 2bstronger** [comment]
我没有mac，但是我觉得应该是这样：
1. 下载 npm
2. 下载项目源代码
3. 在源代码根目录依次执行项目 [wiki](https://github.com/setube/vue-XiuXianGame/wiki/install) 当中的安装步骤

或者安装 docker 工具，按照 [wiki](https://github.com/setube/vue-XiuXianGame/wiki/docker_install) 说明启动容器

**Comment by Raymondwu12** [comment]
<img width="849" alt="截屏2024-09-05 上午12 20 53" src="https://github.com/user-attachments/assets/a7ff8a64-759c-400a-873a-89d1b5d3e9d3">
请问这个这个nvm是什么，应该选哪个

**Comment by setube** [comment]
MacOS安装node.js:`https://cloud.baidu.com/article/3285921`

**Comment by Raymondwu12** [comment]
> MacOS安装node.js:`https://cloud.baidu.com/article/3285921`

emmm，请问安装了以后，下一步干嘛

**Comment by setube** [comment]
> > MacOS安装node.js:`https://cloud.baidu.com/article/3285921`
> 
> emmm，请问安装了以后，下一步干嘛

建议学习一下node.js的相关知识
