### ISSUE TITLE
[功能需求]如何继承当前数据，迁移到其他设备(平台)上玩

### ISSUE THREAD

**Issue by Uggpic** [setube/vue-XiuXianGame#4]
** 需求 **

以下几个建议，希望改善体验：
1*添加继承码方式，用户可以轻松在其他设备上登录原帐号玩

2*pvp模式和聊天闲聊系统...这个可以以后适当开发

3*打包成apk 程序运行可以设置自动修炼和自动打怪

**Comment by setube** [comment]
数据导入功能开始就考虑过,但是一直没落实,等我过两天不忙的时候再更新吧
其他的目前不在考虑范围内

**Comment by setube** [comment]
数据导入功能已添加, 其他到目前没有打算
