### ISSUE TITLE
[BUG反馈]docker方式安装失败

### ISSUE THREAD

**Issue by top-player** [setube/vue-XiuXianGame#40]
[root@localhost ~]# docker pull ccr.ccs.tencentyun.com/wuchen/vue-xiuxiangame
Using default tag: latest
Error response from daemon: manifest for ccr.ccs.tencentyun.com/wuchen/vue-xiuxiangame:latest not found: manifest unknown: manifest unknown

**Comment by setube** [comment]
已更新docker安装方式
