### ISSUE TITLE
[功能需求]优化操作体验及玩法

### ISSUE THREAD

**Issue by yanecc** [setube/vue-XiuXianGame#48]
**需求**

1. 为每个按钮添加快捷键，一直点鼠标太累手了！
2. 添加用其他颜色的格子明确标记的较强精英怪位置，可以有更高概率获得优质装备或收服有更好属性的灵宠
3. 机缘点现在前期没什么用，可以加一些别的机缘或资源点
4. 当前背包满了会自动丢弃新获得的装备或灵宠，希望可以选择丢弃目标或自动丢弃背包中评分最低的

**Comment by setube** [comment]
按钮方面可以说的详细点,其他的我有其他考量
